# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 576809144d0cdc2f06b62f8ef324e906a50a27b509a847e909e8a3b38af336a1052c638eec3d1984dec89e9f62617e4cbbded79d814a72e35e21f79e82d25ff9

test:
  secret_key_base: bc29e6bdb8970ca95cfb9c311eb017c0ea3196a41ac26cec917013dc0320270e2ac4dcbbf4384b6874204b56f4d5c1a4c7b6d26fe0242b07dc00928dbbe2c516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
